<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-JsAm_Signalr-5d4c0639-bec7-41af-9001-a4a4d64a0a2c</UserSecretsId>
        <RootNamespace>JsAm_Signalr</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <None Update="app.db" CopyToOutputDirectory="PreserveNewest" ExcludeFromSingleFile="true"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.11"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.11"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.11"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.11"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.11"/>
    </ItemGroup>

</Project>
